### ISSUE TITLE
Implement `append file` method

### ISSUE THREAD

**Issue by niccord** [Eomm/file-utils-easy#1]
Please, implement an `appendFile` method or change the signature of `writeToFile` adding a parameter in order to decide if append the new string

**Comment by niccord** [comment]
Don't stale, I am going to fix this

**Comment by niccord** [comment]
Please, check PR #4

**Comment by Eomm** [comment]
Released in https://github.com/Eomm/file-utils-easy/releases/tag/v1.2.0
